model : "lstm_ae"
num_layers_ae : 2
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
train_per : 0.7
seq_length : 12
step_size : 24
embed_size : 64
batch_size : 32
lr : 0.00001
num_epochs : 2
