model : "lstm_ae_all"
num_layers_encoder : 1
num_layers_decoder : 1
layer_norm : true
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
standardization : true
train_per : 0.7
seq_length : 5
step_size : 24
embed_size : 10
batch_size : 32
lr : 0.001
num_epochs : 501
plot_step : 100
