model : "lstm_ae"
num_layers_encoder : 3
num_layers_decoder : 3
layer_norm : false
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
standardization : true
train_per : 0.7
seq_length : 5
step_size : 24
embed_size : 50
adam_hd : false
batch_size : 16
lr : 0.0001
dropout : 0.2
num_epochs : 501
plot_step : 100
