model : "cnn_autoencoder_pretraining"
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
standardization : true
train_per : 0.7
step_size : 24
embed_size : 16
batch_size : 32
lr : 0.001
num_epochs : 501
plot_step : 25
