model : "gru_ae_all"
num_layers_encoder : 2
num_layers_decoder : 2
layer_norm : false
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
standardization : true
train_per : 0.7
seq_length : 5
step_size : 24
hidden_size : 50
embed_size : 50
adam_hd : false
batch_size : 32
lr : 0.001
dropout : 0.1
num_epochs : 501
plot_step : 100
