model : "tcn_ae"
num_channels : 8
depth : 4
kernel_size : 3
btk_channels : 4
down_factor : 12
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
standardization : true
train_per : 0.7
sample_size : 120
batch_size : 32
lr : 0.00001
num_epochs : 501
plot_step : 100
