model : "cnn_ae"
residual : true
base_dim : 8
depth : 2
kernel_size : 7
dilation : 1
scale_factor : 4
embed_size : 50
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
standardization : true
train_per : 0.7
sample_size : 128
batch_size : 32
lr : 0.001
num_epochs : 501
plot_step : 10
