model : "cnn_ae"
residual : true
base_dim : 8
depth : 3
kernel_size : 3
dilation : 2
scale_factor : 1
embed_size : 50
seed : 1
results_folder : ""
file : "data/BTCUSDT-1h-data.csv"
data_transform : "logr"
standardization : true
train_per : 0.7
sample_size : 128
batch_size : 32
lr : 0.001
dropout : 0.1
adam_hd : false
num_epochs : 101
plot_step : 10
